### ISSUE TITLE
Zero weights not handled correctly in moe calculations

### ISSUE THREAD

**Issue by thebigbird** [jdjohn215/pollster#3] opened 2021-09-22 14:39 UTC
When cases have zero weight, it appears that MOE is not being calculated correctly.
I can send test data (big dataset). david.eagle@duke.edu

`moe_crosstab(test, var1, var2, weight = wt, unwt_n = T, zscore = 1.96)`

 var1     var2    pct   moe     n unweighted_n
   <fct>    <fct> <dbl> <dbl> <dbl>        <int>
 1 Phone    Blue   37.3 13.3   38.6          386
 2 Phone    Green  44.3 13.7   38.6          386
 3 Phone    Red    18.4 10.7   38.6          386
 4 Airplane Blue   12.0  7.71 368.           523
 5 Airplane Green  42.8 11.7  368.           523
 6 Airplane Red    45.2 11.8  368.           523
 7 Scissors Blue   24.9 12.4  171.           360
 8 Scissors Green  31.4 13.3  171.           360
 9 Scissors Red    43.6 14.2  171.           360
10 Paper    Blue   10.3 13.9  190.           141
11 Paper    Green  38.0 22.2  190.           141
12 Paper    Red    51.7 22.9  190.           141
13 Rock     Blue   69.0 36.9   66.9           47
14 Rock     Green  20.2 32.0   66.9           47
15 Rock     Red    10.8 24.8   66.9           47`

`moe_crosstab(test[test$wt!=0,], var1, var2, weight = wt, unwt_n = T, zscore = 1.96)`

   var1     var2    pct   moe     n unweighted_n
   <fct>    <fct> <dbl> <dbl> <dbl>        <int>
 1 Phone    Blue   37.3 14.9   38.6          173
 2 Phone    Green  44.3 15.3   38.6          173
 3 Phone    Red    18.4 11.9   38.6          173
 4 Airplane Blue   12.0  7.57 368.           302
 5 Airplane Green  42.8 11.5  368.           302
 6 Airplane Red    45.2 11.6  368.           302
 7 Scissors Blue   24.9 11.8  171.           220
 8 Scissors Green  31.4 12.7  171.           220
 9 Scissors Red    43.6 13.5  171.           220
10 Paper    Blue   10.3 11.5  190.           115
11 Paper    Green  38.0 18.4  190.           115
12 Paper    Red    51.7 18.9  190.           115
13 Rock     Blue   69.0 31.1   66.9           37
14 Rock     Green  20.2 27.0   66.9           37
15 Rock     Red    10.8 20.9   66.9           37
`

Produce different results. I don't think they should.

**Comment by jdjohn215** [comment] 2021-09-22 15:19
Hmmm. Thanks for bringing this up. Let me give this issue some thought.

The issue is arising because MoE is calculated using the *unweighted* sample size (incorporating the design effect from the weights). In your first example, the MoE is lower because all those cases where `wt = 0` are still counted toward the sample size. I think this is the correct behavior, because those are still sampled observations.

What do you think?

**Comment by thebigbird** [comment] 2021-09-23 16:00
Yes, that's right the code is counting cases with zero weight in the calculation of N. For samples without clustering. See page 74 of: https://cran.r-project.org/web/packages/survey/survey.pdf where this is documented in the survey package in R.

**Comment by jdjohn215** [comment] 2022-10-26 20:59
This has been fixed in v0.1.4

**Closed as completed by jdjohn215** 2022-10-26 20:59 UTC
